<?php
    $total_space=disk_total_space("data");
    $total_spaces=null;
    if($total_space>=pow(2,10)&&$total_space<pow(2,20)){
        $total_spaces=floor($total_space/pow(2,10))."KB";
    }
    if($total_space>=pow(2,20)&&$total_space<pow(2,30)){
        $total_spaces=floor($total_space/pow(2,20))."MB";
    }
    if($total_space>=pow(2,30)&&$total_space<pow(2,40)){
        $total_spaces=floor($total_space/pow(2,30))."GB";
    }
    if($total_space>=pow(2,40)){
        $total_spaces=floor($total_space/pow(2,40))."TB";
    }
    if($total_space<pow(2,10)){
        $total_spaces=floor($total_space)."B";
    }
    echo $total_spaces;
?>