<?php
    $free_space=disk_free_space("data");
    $total_space=disk_total_space("data");
    $unit=null;
    $total_spaces=null;
    $free_spaces=null;
    $free_space2=$total_space-$free_space;
    if(($total_space-$free_space)>=pow(2,10)&&($total_space-$free_space)<pow(2,20)){
        $free_spaces=floor(($total_space-$free_space)/pow(2,10));
        $unit="KB";
    }
    if(($total_space-$free_space)>=pow(2,20)&&($total_space-$free_space)<pow(2,30)){
        $free_spaces=floor(($total_space-$free_space)/pow(2,20));
        $unit="MB";
    }
    if(($total_space-$free_space)>=pow(2,30)&&($total_space-$free_space)<pow(2,40)){
        $free_spaces=floor(($total_space-$free_space)/pow(2,30));
        $unit="GB";
    }
    if(($total_space-$free_space)>=pow(2,40)){
        $free_spaces=floor(($total_space-$free_space)/pow(2,40));
        $unit="TB";
    }
    if(($total_space-$free_space)<pow(2,10)){
        $free_spaces=floor(($total_space-$free_space));
        $unit="B";
    }
    echo $free_spaces." ".$total_space." ".$free_space2." ".$unit;
?>