<?php
	$dir=$_GET['dir'];
	$keywords=$_GET['keywords'];
	if($keywords!=""){
		keywords_search($keywords,$dir);
	}else{
		dirs_scar($dir);
	}
	$json=null;
	function keywords_search($keywords,$dirs){
		if(is_dir($dirs)){
			if($dh=opendir($dirs)){
				$json='{"sites":[';
				while(($file=readdir($dh))!=false){
					if($file!="."&&$file!=".."){
						if(is_dir($dirs."/".$file)&&preg_match('/'.$keywords.'/',$file)){
							clearstatcache();
							$json=$json.'{"name":'."\"".$file."\"".",".'"id":'."\"".$dirs."/".$file."\"".",".'"date":'."\"".date("Y-m-d",filectime($dirs."/".$file))."\"".'},';
						}
						if(is_file($dirs."/".$file)&&preg_match('/'.$keywords.'/',$file)){
							$size=filesize($dirs."/".$file);
							if($size>=pow(2,10)&&$size<pow(2,20)){
								$sizes=round($size/pow(2,10),1)."KB";
							}
							if($size>=pow(2,20)&&$size<pow(2,30)){
								$sizes=round($size/pow(2,20),1)."MB";
							}
							if($size>=pow(2,30)&&$size<pow(2,40)){
								$sizes=round($size/pow(2,30),1)."GB";
							}
							if($size>=pow(2,40)){
								$sizes=round($size/pow(2,40),1)."TB";
							}
							if($size<pow(2,10)){
								$sizes=round($size,1)."B";
							}
							clearstatcache();
							$json=$json.'{"name":'."\"".$file."\"".",".'"id":'."\"".$dirs."/".$file."\"".",".'"date":'."\"".date("Y-m-d",filectime($dirs."/".$file))."\"".",".'"size":'."\"".$sizes."\"".'},';
						}
					}
				}
				if(substr($json,-1)==","){
					$json=substr($json,0,-1);
				}
				$json=$json.']}';
				echo $json;
			}
		}
	}
	function dirs_scar($dirs){
		if(is_dir($dirs)){
			if($dh=opendir($dirs)){
				$json='{"sites":[';
				while(($file=readdir($dh))!=false){
					if($file!="."&&$file!=".."){
						if(is_dir($dirs."/".$file)){
							clearstatcache();
							$json=$json.'{"name":'."\"".$file."\"".",".'"id":'."\"".$dirs."/".$file."\"".",".'"date":'."\"".date("Y-m-d",filectime($dirs."/".$file))."\"".'},';
						}
						if(is_file($dirs."/".$file)){
							$size=filesize($dirs."/".$file);
							if($size>=pow(2,10)&&$size<pow(2,20)){
								$sizes=round($size/pow(2,10),1)."KB";
							}
							if($size>=pow(2,20)&&$size<pow(2,30)){
								$sizes=round($size/pow(2,20),1)."MB";
							}
							if($size>=pow(2,30)&&$size<pow(2,40)){
								$sizes=round($size/pow(2,30),1)."GB";
							}
							if($size>=pow(2,40)){
								$sizes=round($size/pow(2,40),1)."TB";
							}
							if($size<pow(2,10)){
								$sizes=round($size,1)."B";
							}
							clearstatcache();
							$json=$json.'{"name":'."\"".$file."\"".",".'"id":'."\"".$dirs."/".$file."\"".",".'"date":'."\"".date("Y-m-d",filectime($dirs."/".$file))."\"".",".'"size":'."\"".$sizes."\"".'},';
						}
					}
				}
				if(substr($json,-1)==","){
					$json=substr($json,0,-1);
				}
				$json=$json.']}';
				echo $json;
			}
		}
	}
?>